import { TradeHistoryItem } from '../services/api';
import { buildTxUrl, truncateHash } from '../utils/stellarExplorer';
import SupportLink from '../components/SupportLink';

interface SuccessScreenProps {
    type: 'cashout' | 'deposit';
    trade: TradeHistoryItem & { completed_at: string | null };
    agentName: string;
    onHome: () => void;
}

/** Returns true when the hash was generated by the mock-Stellar backend. */
function isMockHash(hash: string | null | undefined): boolean {
    return !!hash && hash.startsWith('mock');
}

const SuccessScreen = ({ type, trade, agentName, onHome }: SuccessScreenProps) => {
    const amount = trade.amount_mxn.toFixed(2);
    const commission = trade.platform_fee_mxn.toFixed(2);
    const received = (trade.amount_mxn - trade.platform_fee_mxn).toFixed(2);
    const lockTxHash = trade.lock_tx_hash;
    const releaseTxHash = trade.release_tx_hash;

    const isSimulated = isMockHash(lockTxHash) || isMockHash(releaseTxHash);

    const formatTimestamp = (isoString: string | null) => {
        if (!isoString) return '—';
        const date = new Date(isoString);
        const day = date.getDate();
        const month = date.toLocaleString('es-MX', { month: 'short' });
        const hours = date.getHours();
        const minutes = date.getMinutes().toString().padStart(2, '0');
        const ampm = hours >= 12 ? 'pm' : 'am';
        const displayHours = hours % 12 || 12;
        return `${day} ${month} · ${displayHours}:${minutes} ${ampm}`;
    };

    const handleShare = async () => {
        const receiptText = `Recibo de ${type === 'cashout' ? 'retiro' : 'depósito'}${isSimulated ? ' (Simulado — Testnet)' : ''}
Monto: $${amount} MXN
Recibido: $${received} MXN
Comisión: $${commission} MXN
Agente: ${agentName}
Operación ID: ${trade.id}
${lockTxHash ? `Bloqueo: ${truncateHash(lockTxHash, 16)}` : ''}
${releaseTxHash ? `Liberación: ${truncateHash(releaseTxHash, 16)}` : ''}`;

        if (navigator.share) {
            try {
                await navigator.share({
                    title: `Recibo ${type === 'cashout' ? 'Retiro' : 'Depósito'}`,
                    text: receiptText,
                });
                return;
            } catch (err) {
                if ((err as Error).name === 'AbortError') return;
            }
        }

        await navigator.clipboard.writeText(receiptText);
        alert('Recibo copiado al portapapeles');
    };

    return (
        <main className="min-h-screen flex flex-col items-center justify-between px-6 py-12 max-w-md mx-auto bg-surface-container-lowest font-body text-on-surface antialiased">
            {/* Success Header Section */}
            <section className="w-full flex flex-col items-center text-center mt-8">
                {/* Testnet / Simulation badge */}
                {isSimulated && (
                    <div className="mb-4 inline-flex items-center gap-1.5 bg-amber-50 border border-amber-200 text-amber-700 text-xs font-bold uppercase tracking-wider px-3 py-1.5 rounded-full">
                        <span className="material-symbols-outlined text-[14px]">science</span>
                        Testnet · Simulado
                    </div>
                )}

                <div className="bg-[#E1F5EE] w-[72px] h-[72px] rounded-full flex items-center justify-center mb-8 shadow-sm">
                    <span className="material-symbols-outlined text-[#1D9E75] text-[40px]" style={{ fontVariationSettings: '"wght" 600' }}>
                        {type === 'cashout' ? 'check' : 'check_circle'}
                    </span>
                </div>
                <h1 className="font-headline font-extrabold text-4xl tracking-tight mb-2">
                    {type === 'cashout' ? '¡Listo!' : '¡Depósito exitoso!'}
                </h1>
                <p className="text-secondary font-medium text-lg opacity-70">
                    {type === 'cashout' ? 'Recibiste tu efectivo' : 'Tus MXNE ya están en tu billetera'}
                </p>
            </section>

            {/* Summary Card */}
            <section className="w-full bg-[#f6f7f8] rounded-[24px] p-6 my-8 space-y-5 shadow-sm">
                <div className="space-y-4">
                    <div className="flex justify-between items-center">
                        <span className="text-on-surface-variant font-medium text-sm">
                            {type === 'cashout' ? 'MXN enviados' : 'Efectivo entregado'}
                        </span>
                        <span className="font-bold text-on-surface">${amount}</span>
                    </div>
                    <div className="flex justify-between items-center">
                        <span className="text-on-surface-variant font-medium text-sm">
                            {type === 'cashout' ? 'Efectivo recibido' : 'MXNE recibidos'}
                        </span>
                        <span className="font-bold text-primary text-lg">
                            {type === 'cashout' ? `$${received}` : `+${received}`}
                        </span>
                    </div>
                    <div className="flex justify-between items-center">
                        <span className="text-on-surface-variant font-medium text-sm">Comisión</span>
                        <span className="font-medium text-on-surface">-${commission}</span>
                    </div>
                </div>

                <div className="h-[1px] w-full bg-outline-variant/10"></div>

                <div className="space-y-4">
                    <div className="flex justify-between items-start">
                        <span className="text-on-surface-variant font-medium text-sm">Agente</span>
                        <div className="text-right">
                            <p className="font-semibold text-on-surface text-sm">{agentName}</p>
                            <div className="flex items-center justify-end gap-1 mt-0.5 text-primary">
                                <span className="material-symbols-outlined text-[14px]" style={{ fontVariationSettings: '"FILL" 1' }}>verified</span>
                                <span className="text-[10px] font-bold uppercase tracking-wider">Verificado</span>
                            </div>
                        </div>
                    </div>
                    <div className="flex justify-between items-center">
                        <span className="text-on-surface-variant font-medium text-sm">Fecha y hora</span>
                        <span className="text-on-surface text-sm font-medium">{formatTimestamp(trade.completed_at ?? trade.created_at)}</span>
                    </div>
                </div>
            </section>

            {/* Receipt — trade evidence */}
            <section className="w-full bg-white border border-outline-variant/15 rounded-2xl p-5 mb-6 space-y-3">
                <h3 className="text-[11px] font-bold text-outline-variant uppercase tracking-[0.15em] mb-3">Recibo de transacción</h3>

                <div className="flex justify-between items-center">
                    <span className="text-on-surface-variant text-xs">Trade ID</span>
                    <span className="font-mono text-xs text-on-surface">{trade.id.slice(0, 8)}…</span>
                </div>

                <div className="flex justify-between items-center">
                    <span className="text-on-surface-variant text-xs">Estado</span>
                    <span className="text-xs font-semibold text-on-surface capitalize">{trade.status}</span>
                </div>

                {lockTxHash && (
                    <div className="flex justify-between items-center">
                        <span className="text-on-surface-variant text-xs">
                            Lock TX {isMockHash(lockTxHash) && <span className="text-amber-600">(simulado)</span>}
                        </span>
                        {isMockHash(lockTxHash) ? (
                            <span className="font-mono text-xs text-on-surface-variant opacity-60">{truncateHash(lockTxHash, 8)}</span>
                        ) : (
                            <a href={buildTxUrl(lockTxHash)} target="_blank" rel="noopener noreferrer"
                                className="font-mono text-xs text-primary hover:underline">{truncateHash(lockTxHash, 8)}</a>
                        )}
                    </div>
                )}

                {releaseTxHash && (
                    <div className="flex justify-between items-center">
                        <span className="text-on-surface-variant text-xs">
                            Release TX {isMockHash(releaseTxHash) && <span className="text-amber-600">(simulado)</span>}
                        </span>
                        {isMockHash(releaseTxHash) ? (
                            <span className="font-mono text-xs text-on-surface-variant opacity-60">{truncateHash(releaseTxHash, 8)}</span>
                        ) : (
                            <a href={buildTxUrl(releaseTxHash)} target="_blank" rel="noopener noreferrer"
                                className="font-mono text-xs text-primary hover:underline">{truncateHash(releaseTxHash, 8)}</a>
                        )}
                    </div>
                )}

                <div className="flex justify-between items-center">
                    <span className="text-on-surface-variant text-xs">Creado</span>
                    <span className="text-xs text-on-surface">{formatTimestamp(trade.created_at)}</span>
                </div>

                {trade.completed_at && (
                    <div className="flex justify-between items-center">
                        <span className="text-on-surface-variant text-xs">Completado</span>
                        <span className="text-xs text-on-surface">{formatTimestamp(trade.completed_at)}</span>
                    </div>
                )}

                <div className="pt-2 text-center">
                    <SupportLink tradeId={trade.id} state="SUCCESS" />
                </div>
            </section>

            {/* Hash & Rating */}
            <div className="w-full space-y-8 text-center">
                {/* Hashes de operación */}
                <section className="space-y-4">
                    {releaseTxHash && !isMockHash(releaseTxHash) && (
                        <div>
                            <a
                                href={buildTxUrl(releaseTxHash)}
                                target="_blank"
                                rel="noopener noreferrer"
                                className="text-primary font-bold text-sm hover:opacity-80 transition-opacity flex items-center justify-center gap-2 mx-auto"
                            >
                                Ver liberación de la operación
                                <span className="material-symbols-outlined text-[18px]">open_in_new</span>
                            </a>
                            <p className="font-mono text-[11px] text-on-surface-variant opacity-60 tracking-tight mt-1">
                                {truncateHash(releaseTxHash, 8)}
                            </p>
                        </div>
                    )}
                    {lockTxHash && !releaseTxHash && !isMockHash(lockTxHash) && (
                        <div>
                            <a
                                href={buildTxUrl(lockTxHash)}
                                target="_blank"
                                rel="noopener noreferrer"
                                className="text-primary font-bold text-sm hover:opacity-80 transition-opacity flex items-center justify-center gap-2 mx-auto"
                            >
                                Ver bloqueo de la operación
                                <span className="material-symbols-outlined text-[18px]">open_in_new</span>
                            </a>
                            <p className="font-mono text-[11px] text-on-surface-variant opacity-60 tracking-tight mt-1">
                                {truncateHash(lockTxHash, 8)}
                            </p>
                        </div>
                    )}
                    {(!lockTxHash && !releaseTxHash) && (
                        <span className="text-primary font-bold text-sm opacity-40 flex items-center justify-center gap-2">
                            Ver operación en cadena
                            <span className="material-symbols-outlined text-[18px]">open_in_new</span>
                        </span>
                    )}
                </section>

                {/* Share button */}
                <section>
                    <button
                        onClick={handleShare}
                        className="text-primary font-bold text-sm hover:opacity-80 transition-opacity flex items-center justify-center gap-2 mx-auto bg-primary/10 px-4 py-2 rounded-lg"
                    >
                        Compartir recibo
                        <span className="material-symbols-outlined text-[18px]">share</span>
                    </button>
                </section>

                {/* Star rating */}
                <section>
                    <p className="text-on-surface-variant font-medium text-sm mb-4">¿Cómo estuvo el servicio de {agentName}?</p>
                    <div className="flex justify-center gap-2">
                        {[1, 2, 3, 4, 5].map((star) => (
                            <span
                                key={star}
                                className="material-symbols-outlined text-outline-variant text-[32px] cursor-pointer hover:text-primary transition-colors"
                            >
                                star
                            </span>
                        ))}
                    </div>
                </section>
            </div>

            {/* Primary Action */}
            <div className="w-full pt-8">
                <button
                    onClick={onHome}
                    className="w-full h-[54px] bg-gradient-to-r from-primary to-primary-container text-white font-bold rounded-xl shadow-lg shadow-primary/20 active:scale-95 transition-all flex items-center justify-center gap-2"
                >
                    Volver al inicio
                    <span className="material-symbols-outlined">arrow_forward</span>
                </button>
            </div>
        </main>
    );
};

export default SuccessScreen;
